### ISSUE TITLE
Bitcode options are always incorrectly parsed to `false`

### ISSUE THREAD

**Issue by sadlerjw** [bitrise-steplib/steps-export-xcarchive#11]
The config values for the bitcode options are `"yes"` and `"no`", but the code that uses these options converts the string to a boolean: `configs.UploadBitcode == "true"`, which _always_ returns `false`. The generated plist always has:

```plist
<key>uploadBitcode</key>
<false></false>
```

The "Xcode Archive and Export for iOS" step does the check properly: https://github.com/bitrise-steplib/steps-xcode-archive/blob/54295929c7fe6f0beb231ef19c680389839cd1f2/main.go#L677

**Comment by ahvth-bitrise** [comment]
Hi @sadlerjw! Could you please provide a build URL where you see this happening? Thanks! 😄

**Comment by sadlerjw** [comment]
@ahvth-bitrise https://app.bitrise.io/build/12bf50c2df5533ed#?tab=log - thanks!

**Comment by lpusok** [comment]
Hello @sadlerjw ,
A new release is available that fixes this issue: https://github.com/bitrise-steplib/steps-export-xcarchive/releases/tag/2.0.0.
