### ISSUE TITLE
Archive not found when the path contains quotes

### ISSUE THREAD

**Issue by VillSkog** [bitrise-steplib/steps-export-xcarchive#8]
I was using this step to export an zipped archive to iTunes Connect. The archived is unziped with a script and then available at this path `"${BITRISE_DEPLOY_DIR}/${BITRISE_SCHEME}.xcarchive"`. But I always got this error : Issue with input: ArchivePath not exist at: "***".
When I removed the quotes in the step config, it worked (the path doesn't contain spaces). But I guess this would be a bug for an app name containing spaces.

**Comment by viktorbenei** [comment]
Do you mean you included `""` in the input in the workflow editor? If you mean that then it's not required, as those parameters are passed as env vars. The specific step which will handle that path is required to escape it if needed, but you as the user should just provide the value, without any quotes / escaping, as that will be passed as a String (env vars are simple string data type) to the step.

If I misunderstood the issue just let me know!
Happy Building! :)
